### ISSUE TITLE
Breaks Php Files?

### ISSUE THREAD

**Issue by mohsinr** [shkuznetsov/gulp-minify-inline#12]
Hi,

Thanks for writing awesome plugin, it does great job to minifying the inline JS and CSS. 
Just one issue I am facing is that if I run php files through it , it will break the php files, one thing I found specially was that it had replaced the <?php with just 'php' ...

**Comment by shkuznetsov** [comment]
Aha... could you please supply an example of the source file being broken, I'll have a look what can be done.

**Comment by shkuznetsov** [comment]
Hi. So I tried to reproduce the issue you mentioned without much luck -- my PHP code doesn't get mangled or broken. I'm closing this one -- please re-open with an example code if the issue persists for you. Thanks!
