### ISSUE TITLE
<?php ?> inside HTML tags break.

### ISSUE THREAD

**Issue by joedajigalo** [shkuznetsov/gulp-minify-inline#13]
So it seems this is pin pointed to when gulp minify inline runs for js.

The original code: 
PRE MINIFY
`<body <?php body_class(); ?>>`

GULP MINIFY INLINE
`<body <?php="" body_class();="" ?="">>`

You can see it adds `=""`

I don't know how to exactly pin point the pipe to exclude inline tags inside of HTML Tags.
`
.pipe($.if('*.php', $.minifyInline({
  js: false
})))
`
Prevents the issue, but I believe it also does not minify `<script>` tags.

**Comment by tomasdev** [comment]
Why.... just why are you trying to use an HTML minimizer for PHP minimizing?!?!

You can just use the following:
```php
ob_start(function($b){
    return preg_replace(['/\>[^\S ]+/s','/[^\S ]+\</s','/(\s)+/s'],['>','<','\\1'],$b);
});
```

More information at http://stackoverflow.com/questions/6225351/how-to-minify-php-page-html-output

**Comment by shkuznetsov** [comment]
Yes, I kind of agree with @tomasdev... I understand you want to minify a PHP template before rendering JS/HTML output, but the minification library is not aware of PHP syntax, neither it aware of any other non-JS/HTML syntaxes. So in your case the solution would be to bypass PHP files, pretty much the way you're doing it already.
