### ISSUE TITLE
Fully minify HTML?

### ISSUE THREAD

**Issue by tomasdev** [shkuznetsov/gulp-minify-inline#16]
If you minify the following:
```html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/contentful-ui-extensions-sdk@2/dist/cf-extension.css">
<style>
section {
  border-bottom: 1px solid rgba(0, 0, 0, .2);
  padding-bottom: 2em;
  margin-bottom: 2em;
}
.cf-form-field {
  margin-left: 1em;
}
</style>
</head>
<body>
  <div id="content"></div>
  <script src="https://unpkg.com/contentful-ui-extensions-sdk@2"></script>
</body>
</html>
```

Produces the following:
```html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/contentful-ui-extensions-sdk@2/dist/cf-extension.css">
<style>section{border-bottom:1px solid rgba(0,0,0,.2);padding-bottom:2em;margin-bottom:2em}.cf-form-field{margin-left:1em}</style>
</head>
<body>
<div id="content"></div>
<script src="https://unpkg.com/contentful-ui-extensions-sdk@2"></script>
</body>
</html>
```

Instead of:
```html
<!DOCTYPE html><html><head><link rel="stylesheet" type="text/css" href="https://unpkg.com/contentful-ui-extensions-sdk@2/dist/cf-extension.css"><style>section{border-bottom:1px solid rgba(0,0,0,.2);padding-bottom:2em;margin-bottom:2em}.cf-form-field{margin-left:1em}</style></head><body><div id="content"></div><script src="https://unpkg.com/contentful-ui-extensions-sdk@2"></script></body></html>
```

Is there any configuration option for removing new lines?

**Comment by joedajigalo** [comment]
Hey @tomasdev,

Have you tried using gulp-minify-inline w/ [Web Starter Kit](https://github.com/google/web-starter-kit)?

You can use WSK for development locally, and when you're ready to build, it will minify the HTML, and `gulp-minify-inline` will minify the inline css and js.

Here is an example: [josephvan.xyz](http://josephvan.xyz/)

![image](https://cloud.githubusercontent.com/assets/4065657/23842091/e6f8dba2-077f-11e7-99bc-ccbc6da82e50.png)

Notice my JS is inline - but when I am building, it is minified:

![image](https://cloud.githubusercontent.com/assets/4065657/23842109/fb4c63c6-077f-11e7-9cf4-22ea40f209ba.png)

Let me know if this is what you are considering to do.

**Comment by tomasdev** [comment]
I ended up using nginx pagespeed to minify the output.
