### ISSUE TITLE
Causes 'Uncaught SyntaxError: Unexpected token ILLEGAL'

### ISSUE THREAD

**Issue by craigmdennis** [shkuznetsov/gulp-minify-inline#4]
This is the only js in my `<head>` that is inside a script tag.

```js
// Add .js class if not using Modernizr
document.documentElement.className = 'js';

// Show :active styles on touch devices
document.addEventListener('touchstart', function(){}, true);
```

**Comment by haydenbleasel** [comment]
+1

**Comment by shkuznetsov** [comment]
Sorry could you please clarify that a bit? I can't reproduce the error.

**Comment by shkuznetsov** [comment]
Sorry closing that due to not being reproducible or followed up on. Please re-open with more details if the issue persists.
